"""add Daily Consumption

Revision ID: 573bbdbddfdb
Revises: eadd2785810e
Create Date: 2025-07-31 07:46:27.304151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573bbdbddfdb'
down_revision: Union[str, Sequence[str], None] = 'eadd2785810e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('birt_date', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('height', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'birt_date')
    op.drop_table('daily_consumptions')
    # ### end Alembic commands ###
