"""menambahkan tabel weight history

Revision ID: 8551fea4b62b
Revises: aa27b865200b
Create Date: 2025-08-13 21:06:36.448296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8551fea4b62b'
down_revision: Union[str, Sequence[str], None] = 'aa27b865200b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_history')
    op.create_foreign_key(None, 'daily_consumptions', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    # op.drop_constraint(None, 'users', type_='unique')
    # op.drop_constraint(None, 'daily_consumptions', type_='foreignkey')
    op.create_table('weight_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('weight_history', sa.Integer, nullable=False))
    op.create_foreign_key(None, 'weight_histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
