"""initial

Revision ID: aa27b865200b
Revises: 
Create Date: 2025-08-09 21:28:40.500341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa27b865200b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_consumptions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'daily_consumptions', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'daily_consumptions', type_='foreignkey')
    op.drop_column('daily_consumptions', 'user_id')
    # ### end Alembic commands ###
