"""create users

Revision ID: eadd2785810e
Revises: 
Create Date: 2025-07-30 22:32:28.893657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadd2785810e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'birt_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birt_date', sa.DATE(), nullable=False))
    op.add_column('users', sa.Column('height', sa.FLOAT(), nullable=False))
    op.add_column('users', sa.Column('weight', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
